django_app/category/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='list'),
    path('create', views.CategoryCreateView.as_view(), name='add'),
    path('<int:pk>/edit', views.CategoryUpdateView.as_view(), name='edit'),
]

django_app/feed_notifier/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('api/', include(('jobs.api.urls', 'jobs'), namespace='api')),
    path('admin/', admin.site.urls),
    path('hello', views.hello),
    path('feeds/', include(('feeds.urls', 'feeds'), namespace='feeds')),
    path('category/', include(('category.urls', 'category'), namespace='category'))
]

django_app/feeds/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FeedListView.as_view(), name='list'),
    path('add', views.FeedCreateView.as_view(), name='add'),
    path('<int:pk>', views.FeedDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.FeedEditView.as_view(), name='edit')
]

django_app/jobs/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('job/', views.create_job, name='create-job'),
    path('job/<id>', views.check_job, name='check-job')
]

django_app/category/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        pass
        # return reverse_lazy('category:detail', args=[self.id])

django_app/feeds/models.py
from django.db import models
from django.urls import reverse
from category.models import Category

# Create your models here.

class Feed(models.Model):
    title = models.CharField(max_length=200)
    url = models.URLField()
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 related_name='feeds')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('feeds:detail', args=[self.id])

django_app/jobs/models.py
from django.db import models

# Create your models here.

django_app/category/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from .models import Category
from django.urls import reverse_lazy

# Create your views here.

class CategoryListView(ListView):
    model = Category
    template_name = 'category/list.html'

class CategoryCreateView(CreateView):
    model = Category
    template_name = 'category/manipulate.html'
    fields = ['name']
    success_url = reverse_lazy('category:list')

class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'category/manipulate.html'
    fields = ['name']
    success_url = reverse_lazy('category:list')

# https://stackoverflow.com/questions/3011179/django-the-included-urlconf-doesnt-have-any-patterns-in-it

django_app/feed_notifier/views.py
from django.http import HttpResponse
from django.shortcuts import render

def hello(request):
    return render(request, 'base.html')

django_app/feeds/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.urls import reverse
from .models import Feed

# Create your views here.

class FeedListView(ListView):
    model = Feed
    template_name = 'feeds/list.html'

class FeedCreateView(CreateView):
    model = Feed
    template_name = 'feeds/add.html'
    fields = ['title', 'url', 'description', 'category']

class FeedDetailView(DetailView):
    model = Feed
    template_name = 'feeds/detail.html'
    
    def get_context_data(self, **kwargs):
        context = super(FeedDetailView, self).get_context_data(**kwargs)
        context['props'] = {
            'id': self.object.id,
            'url': reverse('api:create-job')
        }
        return context

class FeedEditView(UpdateView):
    model = Feed
    template_name = 'feeds/add.html'
    fields = ['title', 'url', 'description', 'category']

django_app/jobs/api/views.py
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from rest_framework.parsers import JSONParser
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from celery.result import AsyncResult 
from .serializers import JobCreateSerializer

from feeds.tasks import get_feed
from feeds.models import Feed


accepted_jobs = {
    'get_feed': get_feed
}

@csrf_exempt
@api_view(['POST'])
def create_job(request):
    data = JSONParser().parse(request)
    serialized = JobCreateSerializer(data=data)
    if serialized.is_valid():

        job_type = accepted_jobs.get(serialized.data['type'])

        if job_type:
            feed = get_object_or_404(Feed, pk=serialized.data.get('id'))

            task = getattr(job_type, 'delay')(feed.url, no_cache=serialized.data.get('no_cache'))

            result = {
                'url': reverse('api:check-job', args=[task.id])
            }

            return Response(result, status=200)
    return Response({'error': True}, status=400)


@api_view(['GET'])
def check_job(request, id):
    task = AsyncResult(id)

    result = {
        'status': task.status,
        'result': task.result
    }

    return Response(result, status=200)

django_app/jobs/views.py
from django.shortcuts import render

# Create your views here.

django_app/category/templates/category/list.html
{% extends 'base.html' %}
{% block title %}Categories{% endblock %}

{% block content %}
<section>
        <div class="container-fluid">
          <!-- Page Header-->
          <header> 
            <h1 class="h3 display">Category List</h1>
          </header>

          <div class="row mb-4">
            <div class="col">
              <a href="{% url 'category:add' %}" class="btn btn-info ml-auto"><i class="fa fa-plus"></i> Add Category</a>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="card">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Feeds Count</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for category in object_list %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></td>
                          <td>{{ category.feeds.count }}</td>
                          <td><a class="btn btn-primary" href="{% url 'category:edit' category.id %}">Edit</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                          <td colspan=4 class='text-center'>No data found.</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
            
            
          </div>
        </div>
      </section>
{% endblock %}

django_app/category/templates/category/manipulate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% if object %}Edit {{ object.title }} {% else %} Add New Category {% endif %}{% endblock %}

{% block content %}

<section>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="{% if object %}Save{% else %}Add New{% endif %}" class="btn btn-primary">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

django_app/feeds/templates/feeds/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{% if object %}Edit {{ object.title }} {% else %} Add new feed {% endif %}{% endblock %}

{% block content %}

<section>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="{% if object %}Save{% else %}Add New{% endif %}" class="btn btn-primary">
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

django_app/feeds/templates/feeds/detail.html
{% extends 'base.html' %}
{% load render_bundle from webpack_loader %}

{% block title %}Detail {{ object.title }}{% endblock %}

{% block content %}
<section>
  <div class="container-fluid">
    <header>
      <h1>Detail of {{object.title}} 
        <a href="{% url 'feeds:edit' object.id %}" class='btn btn-lg'><i class="fa fa-pencil"></i> Edit</a>
      </h1>
    </header>

    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <ul class="list-group">
              <li class="list-group-item">
                <a href="{{ object.url }}">{{ object.url | truncatechars:50 }}</a></li>
              <li class="list-group-item">{{ object.description|linebreaks }}</li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            {{ props|json_script:'props' }}
            <script>
              window.previewProps = JSON.parse(document.getElementById('props').textContent);
            </script>
            <div id="preview-id"><i class="fa fa-spin fa-spinner"></i> Please Wait While Loading Component</div>
            {% render_bundle 'preview' %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

django_app/feeds/templates/feeds/list.html
{% extends 'base.html' %}

{% block title %}Feeds List{% endblock %}

{% block content %}
<section>
        <div class="container-fluid">
          <!-- Page Header-->
          <header> 
            <h1 class="h3 display">Feed List</h1>
          </header>

          <div class="row mb-4">
            <div class="col">
              <a href="{% url 'feeds:add' %}" class="btn btn-info ml-auto"><i class="fa fa-plus"></i> Add Feed</a>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="card">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Title</th>
                          <th>Url</th>
                          <th>Description</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for feed in object_list %}
                        <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td><a href="{{ feed.get_absolute_url }}">{{ feed.title }}</a></td>
                          <td><a href="{{ feed.url }}">{{ feed.url | truncatechars:50 }}</a> </td>
                          <td>{{ feed.description| truncatewords:5 }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                          <td colspan=4 class='text-center'>No data found.</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            
            
            
          </div>
        </div>
      </section>
{% endblock %}

django_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Bootstrap Dashboard by Bootstrapious.com{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css'  %}">

    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="{% static 'css/grasp_mobile_progress_circle-1.0.0.min.css'  %}">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="{% static 'vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css'  %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css'  %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css'  %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico'  %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>

    <!-- Side Navbar -->
    {% include 'components/sidebar.html' %}
    
    <div class="page">
      {% include 'components/header.html' %}
      {% block content %}{% endblock %}
      <footer class="main-footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <p>Your company &copy; 2017-2019</p>
            </div>
            <div class="col-sm-6 text-right">
              <p>Design by <a href="https://bootstrapious.com" class="external">Bootstrapious</a></p>
              <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions and it helps me to run Bootstrapious. Thank you for understanding :)-->
            </div>
          </div>
        </div>
      </footer>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/grasp_mobile_progress_circle-1.0.0.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/charts-home.js' %}"></script>
    <!-- Main File-->
    <script src="{% static 'js/front.js' %}"></script>
  </body>
</html>

django_app/templates/components/header.html
{% load static %}
<header class="header">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
                  <div class="brand-text d-none d-md-inline-block"><span>Bootstrap </span><strong class="text-primary">Dashboard</strong></div></a></div>
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <!-- Notifications dropdown-->
                <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell"></i><span class="badge badge-warning">12</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item"> 
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-envelope"></i>You have 6 new messages </div>
                          <div class="notification-time"><small>4 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item"> 
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                          <div class="notification-time"><small>4 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item"> 
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-upload"></i>Server Rebooted</div>
                          <div class="notification-time"><small>4 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item"> 
                        <div class="notification d-flex justify-content-between">
                          <div class="notification-content"><i class="fa fa-twitter"></i>You have 2 followers</div>
                          <div class="notification-time"><small>10 minutes ago</small></div>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-bell"></i>view all notifications                                            </strong></a></li>
                  </ul>
                </li>
                <!-- Messages dropdown-->
                <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope"></i><span class="badge badge-info">10</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-profile"> <img src="{% static 'img/avatar-1.jpg' %}" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Jason Doe</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-profile"> <img src="{% static 'img/avatar-2.jpg' %}" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Frank Williams</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-profile"> <img src="{% static 'img/avatar-3.jpg' %}" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="msg-body">
                          <h3 class="h5">Ashley Wood</h3><span>sent you a direct message</span><small>3 days ago at 7:58 pm - 10.06.2014</small>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong> <i class="fa fa-envelope"></i>Read all messages    </strong></a></li>
                  </ul>
                </li>
                <!-- Languages dropdown    -->
                <li class="nav-item dropdown"><a id="languages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link language dropdown-toggle"><img src="{% static 'img/flags/16/GB.png' %}" alt="English"><span class="d-none d-sm-inline-block">English</span></a>
                  <ul aria-labelledby="languages" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item"> <img src="{% static 'img/flags/16/DE.png' %}" alt="English" class="mr-2"><span>German</span></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item"> <img src="{% static 'img/flags/16/FR.png' %}" alt="English" class="mr-2"><span>French                                                         </span></a></li>
                  </ul>
                </li>
                <!-- Log out-->
                <li class="nav-item"><a href="login.html" class="nav-link logout"> <span class="d-none d-sm-inline-block">Logout</span><i class="fa fa-sign-out"></i></a></li>
                <li class="nav-item"><a href="/admin" class="nav-link logout"> <span class="d-none d-sm-inline-block">Go To Admin</span><i class="fa fa-sign-out"></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

django_app/templates/components/sidebar.html
{% load static %}
<nav class="side-navbar">
      <div class="side-navbar-wrapper">
        <div class="sidenav-header d-flex align-items-center justify-content-center">
          <div class="sidenav-header-inner text-center"><img src="https://scontent-sin6-1.xx.fbcdn.net/v/t1.0-9/15492322_1851224868453145_2286480518042878962_n.jpg?_nc_cat=107&_nc_eui2=AeFLEAfGKFyBksiamUen2shPKoxsD-OZejRw9kDVceVdF3T3RFQL9nbrtL0xPGo0dGRaWhgoUrq71sP5uah76Z_AzyrUdhhDsFlelNSglsvS5w&oh=23ff17acde80b2e38ed65f460071d1ed&oe=5C1984CA" alt="person" class="img-fluid rounded-circle">
            <h2 class="h5">Ihfazhillah</h2><span>Web Developer</span>
          </div>
          <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong>B</strong><strong class="text-primary">D</strong></a></div>
        </div>
        <div class="main-menu">
          <ul id="side-main-menu" class="side-menu list-unstyled">                  

            <li><a href="{% url 'feeds:list' %}"><i class="fa fa-rss-square"></i> Feeds</a></li>
            <li><a href="{% url 'category:list' %}"><i class="fa fa-tags"></i> Category</a></li>
            <!--
            <li><a href="index.html"> <i class="icon-home"></i>Home                             </a></li>
            <li><a href="forms.html"> <i class="icon-form"></i>Forms                             </a></li>
            <li><a href="charts.html"> <i class="fa fa-bar-chart"></i>Charts                             </a></li>
            <li><a href="tables.html"> <i class="icon-grid"></i>Tables                             </a></li>
            <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
              <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                <li><a href="#">Page</a></li>
                <li><a href="#">Page</a></li>
                <li><a href="#">Page</a></li>
              </ul>
            </li>
            <li><a href="login.html"> <i class="icon-interface-windows"></i>Login page                             </a></li>
            <li> <a href="#"> <i class="icon-mail"></i>Demo
                <div class="badge badge-warning">6 New</div></a></li>
          </ul>
        </div>
        <div class="admin-menu">
          <h5 class="sidenav-heading">Second menu</h5>
          <ul id="side-admin-menu" class="side-menu list-unstyled"> 
            <li> <a href="#"> <i class="icon-screen"> </i>Demo</a></li>
            <li> <a href="#"> <i class="icon-flask"> </i>Demo
                <div class="badge badge-info">Special</div></a></li>
            <li> <a href=""> <i class="icon-flask"> </i>Demo</a></li>
            <li> <a href=""> <i class="icon-picture"> </i>Demo</a></li>-->
          </ul>
        </div>
      </div>
    </nav>

django_app/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Dashboard by Bootstrapious.com</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="css/fontastic.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="css/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.ico">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="page login-page">
      <div class="container">
        <div class="form-outer text-center d-flex align-items-center">
          <div class="form-inner">
            <div class="logo text-uppercase"><span>Bootstrap</span><strong class="text-primary">Dashboard</strong></div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
            <form method="get" class="text-left form-validate">
              <div class="form-group-material">
                <input id="login-username" type="text" name="loginUsername" required data-msg="Please enter your username" class="input-material">
                <label for="login-username" class="label-material">Username</label>
              </div>
              <div class="form-group-material">
                <input id="login-password" type="password" name="loginPassword" required data-msg="Please enter your password" class="input-material">
                <label for="login-password" class="label-material">Password</label>
              </div>
              <div class="form-group text-center"><a id="login" href="index.html" class="btn btn-primary">Login</a>
                <!-- This should be submit button but I replaced it with <a> for demo purposes-->
              </div>
            </form><a href="#" class="forgot-pass">Forgot Password?</a><small>Do not have an account? </small><a href="register.html" class="signup">Signup</a>
          </div>
          <div class="copyrights text-center">
            <p>Design by <a href="https://bootstrapious.com" class="external">Bootstrapious</a></p>
            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
          </div>
        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/popper.js/umd/popper.min.js"> </script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/chart.js/Chart.min.js"></script>
    <script src="vendor/jquery-validation/jquery.validate.min.js"></script>
    <script src="vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Main File-->
    <script src="js/front.js"></script>
  </body>
</html>